import { StyleSheet, Platform } from 'react-native';
import { Colors, Spacing, Radius, Shadows, Typography } from '../../constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background.secondary,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingBottom: Spacing.xl,
  },
  header: {
    paddingTop: Platform.OS === 'ios' ? Spacing.xxl + Spacing.xl : Spacing.xxl,
    paddingBottom: Spacing.xxl * 2,
    paddingHorizontal: Spacing.md,
    borderBottomLeftRadius: Radius.xl * 2,
    borderBottomRightRadius: Radius.xl * 2,
  },
  logoContainer: {
    alignItems: 'center',
  },
  logoCircle: {
    width: 80,
    height: 80,
    borderRadius: Radius.full,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: Spacing.md,
  },
  appName: {
    fontSize: 32,
    fontWeight: '700',
    color: Colors.text.inverse,
    marginBottom: Spacing.xs,
    letterSpacing: -0.5,
  },
  tagline: {
    fontSize: 15,
    color: 'rgba(255, 255, 255, 0.9)',
    textAlign: 'center',
  },
  formCard: {
    backgroundColor: Colors.background.card,
    marginHorizontal: Spacing.md,
    marginTop: -Spacing.xxl * 1.5,
    borderRadius: Radius.xl,
    paddingTop: Spacing.lg,
    paddingBottom: Spacing.xl,
    paddingHorizontal: Spacing.lg,
    ...Shadows.lg,
    elevation: 8,
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: Colors.background.secondary,
    borderRadius: Radius.md,
    padding: Spacing.xs,
    marginBottom: Spacing.xl,
  },
  tab: {
    flex: 1,
    paddingVertical: Spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Radius.sm,
    position: 'relative',
  },
  activeTab: {
    backgroundColor: Colors.background.card,
    ...Shadows.sm,
  },
  tabText: {
    fontSize: 15,
    fontWeight: '600',
    color: Colors.text.secondary,
  },
  activeTabText: {
    color: Colors.primary.main,
    fontWeight: '700',
  },
  tabIndicator: {
    position: 'absolute',
    bottom: -4,
    left: '25%',
    right: '25%',
    height: 3,
    backgroundColor: Colors.primary.main,
    borderRadius: Radius.full,
  },
  formContent: {
    gap: Spacing.md,
  },
  inputGroup: {
    marginBottom: Spacing.xs,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: Colors.text.primary,
    marginBottom: Spacing.xs,
  },
  input: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.background.secondary,
    borderRadius: Radius.md,
    paddingHorizontal: Spacing.md,
    height: 52,
    borderWidth: 1,
    borderColor: Colors.border.light,
  },
  inputError: {
    borderColor: Colors.error,
    backgroundColor: `${Colors.error}05`,
  },
  inputIcon: {
    marginRight: Spacing.sm,
  },
  textInput: {
    flex: 1,
    fontSize: 15,
    color: Colors.text.primary,
    padding: 0,
    height: '100%',
  },
  passwordContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.background.secondary,
    borderRadius: Radius.md,
    paddingLeft: Spacing.md,
    height: 52,
    borderWidth: 1,
    borderColor: Colors.border.light,
  },
  eyeButton: {
    paddingHorizontal: Spacing.md,
    height: '100%',
    justifyContent: 'center',
  },
  errorText: {
    fontSize: 12,
    color: Colors.error,
    marginTop: Spacing.xs,
    marginLeft: Spacing.xs,
  },
  forgotPasswordButton: {
    alignSelf: 'flex-end',
    paddingVertical: Spacing.xs,
  },
  forgotPasswordText: {
    fontSize: 14,
    fontWeight: '600',
    color: Colors.primary.main,
  },
  submitButton: {
    borderRadius: Radius.md,
    overflow: 'hidden',
    marginTop: Spacing.md,
    height: 52,
    ...Shadows.md,
    elevation: 6,
  },
  disabledButton: {
    opacity: 0.6,
    ...Shadows.sm,
    elevation: 2,
  },
  submitButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.sm,
    height: '100%',
    paddingHorizontal: Spacing.lg,
  },
  submitButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: Colors.text.inverse,
  },
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: Spacing.lg,
  },
  divider: {
    flex: 1,
    height: 1,
    backgroundColor: Colors.border.light,
  },
  dividerText: {
    fontSize: 13,
    color: Colors.text.tertiary,
    marginHorizontal: Spacing.md,
    fontWeight: '500',
  },
  socialButtonsContainer: {
    flexDirection: 'row',
    gap: Spacing.md,
    justifyContent: 'center',
  },
  socialButton: {
    width: 56,
    height: 56,
    borderRadius: Radius.md,
    backgroundColor: Colors.background.secondary,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.border.light,
    ...Shadows.sm,
  },
  termsText: {
    fontSize: 12,
    color: Colors.text.secondary,
    textAlign: 'center',
    marginTop: Spacing.lg,
    lineHeight: 18,
    paddingHorizontal: Spacing.sm,
  },
  termsLink: {
    color: Colors.primary.main,
    fontWeight: '600',
  },
  bottomSpacer: {
    height: Spacing.xl,
  },
  });